name: Rust

on:
  push:
    branches: [ dev, stable ]
  pull_request:
    branches: [ dev, stable ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add wasm toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-2021-06-17
        target: wasm32-unknown-unknown
        override: true
    - name: Build
      run: cargo build
    - name: Run unit tests
      run: cargo test --verbose --features runtime-benchmarks

  deploy:

    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev'

    steps:
    - uses: actions/checkout@v2
    - name: Docs
      run: |
        cargo doc --no-deps --all-features
        echo "<meta http-equiv=\"refresh\" content=\"0; URL=pallet_account_linker/index.html\"/>" > target/doc/index.html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: target/doc
